#!/bin/bash

function Coloring {
NC='\033[0m'
LRED='\033[1;31m'
LGREEN='\033[1;32m'
YELLOW='\033[1;33m'
PURPLE='\033[1;35m'
LBLUE='\033[1;36m'
}



clear
Coloring
sleep 0.2

if [ -f $HOME/AKMODPUBG/obb ]; then
chmod +x $HOME/AKMODPUBG/obb
mv $HOME/AKMODPUBG/obb $PREFIX/bin
fi
function redirect {
if [ -f $HOME/AKMODPUBG/nanamod96 ]; then
chmod +x nanamod96
./nanamod96
fi
}

echo -e "${LGREEN}CHECKING INSTALL TOOL${NC}"
echo -e "${LGREEN}Checking Required packages${NC}"
packages=("wget" "unzip" "libandroid-wordexp" "libandroid-wordexp-static" "zip" "curl" "rsync" "x11-repo" "pv" "figlet" "toilet"  "qemu-system-i386" "qemu-user-i386")
for pkg in ${packages[@]}; do
is_pkg_installed=$(dpkg-query -W --showformat='${Status}
' ${pkg} | grep "install ok installed")
if [ "${is_pkg_installed}" == "install ok installed" ]; then
echo -e ${LGREEN}${pkg}${NC} is installed.
else [ "" = "${is_pkg_installed}" ];
echo -e "${LRED}No ${pkg}. Setting up ${pkg}.${NC}"
pkg install ${pkg} -y
fi
done
redirect
